version: '3.8'
services:
  web:
    image: ghcr.io/reddexx/mysigmail:latest
    ports:
      - "8080:80"
    restart: unless-stopped
    pull_policy: always
    environment:
      VITE_AWS_S3_URL: ""
      VITE_AWS_S3_BASKET: ""
      VITE_AWS_S3_ID: ""
      VITE_AWS_S3_KEY: ""
      VITE_AWS_S3_REGION: ""
